### ISSUE TITLE
Is it possible to disable ligatures?

### ISSUE THREAD

**Issue by tssm** [akiyosi/goneovim#108]
My understanding of [this thread](https://github.com/akiyosi/goneovim/issues/63) is that ligatures are not supported anymore, however I see 🧐 Is it possible to disable them?

**Comment by akiyosi** [comment]
Currently supports ligatures.
You can set the font which support ligatures with `set guifont`.

**Comment by tssm** [comment]
Ah, I see. Is it possible to disable them? I find ligatures quite confusing 😅

**Comment by akiyosi** [comment]
Sorry, I seem to have jumped to the conclusion.
It cannot be disabled at this time, but I think there is an interface to disable on Qt side. I will examine it.

**Comment by tssm** [comment]
Ah, I see. I'll left this open in case someone else wonders the same, but I found that my font of choice now has a version without ligatures 💜

One more (slightly) related thing: `set guifont` seems to work if it is declared on `init.vim`, but not if it is declared on `ginit.vim` (which is being used by other GUIs for custom settings wrapped by an if block)

**Comment by akiyosi** [comment]
Hi
I'm sorry to reply late.

> Ah, I see. I'll left this open in case someone else wonders the same, but I found that my font of choice now has a version without ligatures 💜

That's good. Actually, I checked the interface on the Qt side, and found that it seems to be difficult with the current drawing architecture.

> One more (slightly) related thing: set guifont seems to work if it is declared on init.vim, but not if it is declared on ginit.vim (which is being used by other GUIs for custom settings wrapped by an if block)

Currently, goneovim does not support configure with `ginit.vim`. The reason is that there is no need to use it as an application. All the necessary settings can be written in `init.vim`.

Also, if you have a vimscript that you want to defer after launching the GUI (e.g. To disable a specific setting added by goneovim when the application is launched), you can write a vimscript in setting.toml as the following:

``` toml
[Editor]
# Note that the vimscript parsing process of goneovim is incomplete, so double quoting is not available now.
GinitVim = '''
  let g:yourvar = buzz
  ...
'''
```

As I understand it, ginit.vim was provided by neovim-qt to provide a font configuration interface, since early neovim front-end features didn't provide a configuration interface for guifont, etc.
However, in the current neovim front-end interface, they can be configured by init.vim. Of course, one might argue that neovim-qt is the de facto neovim GUI and that, from a compatibility perspective, it should be loaded with ginit.vim.
