### ISSUE TITLE
CTRL-^ Doesn't Work Without SHIFT

### ISSUE THREAD

**Issue by ewhac** [akiyosi/goneovim#109]
In Vim, the default binding of CTRL-^ switches to the "alternate" file, something I use a lot.  On a normal console, pressing CTRL-6 is sufficient to yield ASCII 0x1e (a/k/a control-uparrow).  This also works in GVim and nvim-qt.

However, goneovim interprets CTRL-6 as if one had simply pressed `6` (you can see sixes accumulating as a count in the command bar).  To get CTRL-^ behavior, you must also hold down SHIFT.

**Comment by akiyosi** [comment]
Hi
Thanks for reporting this issue.

Goneovim is currently just working on solving the problem around the input. I've implemented the same implementation and testing as neovim-qt in the following commits, so expect your issues to be fixed in the next release.

https://github.com/akiyosi/goneovim/commit/2c8dfb247f05f56eb704e177231fba141166d9a9

**Comment by akiyosi** [comment]
Could you please check this issue in v0.4.6?

If the problem has been fixed, we would like to close this issue.

**Comment by eyalk5** [comment]
Not solved for me.

**Comment by ewhac** [comment]
I haven't tested it comprehensively, but so far it appears to be working for me.

**Comment by lourenci** [comment]
It does not work for me even with the SHIFT key.

**Comment by akiyosi** [comment]
@lourenci 
Hi,
What is the OS you are using?
Also, I'm guessing you are using v0.4.12, but could you please check if the problem still occurs with the latest CI build below?
https://github.com/akiyosi/goneovim/actions/runs/1202226984

**Comment by lourenci** [comment]
macOS Monterey.

The built version works like a charm.

Thanks.
