### ISSUE TITLE
M- mappings don't work

### ISSUE THREAD

**Issue by smackesey** [akiyosi/goneovim#129]
I have many M- mappings in my init.vim, and none of them that I've tried work except for those that also use D (e.g. D-M-h). I'm on mac and using alt for meta. I'm guessing this is because alt is not being converted to meta? Is there an option for this (VimR has this). If not, there should be, this makes it quite difficult to try goneovim with the same config that I use for all my other vim variants.

**Comment by akiyosi** [comment]
Hi :)
On MacOS, Goneovim will input the special characters when input keys using the Meta(Option/Alt) key, so you'll need some tricks to define mapping well. 
For example, the input of option+p will be converted to π. so, you need to write the mapping using the string π instead of <M-p>;

```
nnoremap π gT
```

The special characters used for the mapping can be confirmed by actually typing a key with the option key in insert mode.

Of course, there is a plan to add option to possible to add a special mode of operation to goneovim, depending on the configuration, so that it can be mapped with a familiar representation starting with an M-prefix instead of such a special letter. 
I may add such an option in the future, but at the moment it is not yet implemented.

By the way, I'd like to know what other applications you're using vim/neovim for on macOS.

**Comment by smackesey** [comment]
Thanks for your prompt response.

I am currently primarily using VimR, but sometimes also use terminal neovim, and have used MacVim for years. All three of these work with M- mappings. It is good to know that there is a workaround, but it sounds pretty laborious. I'll wait until M- mappings are supported before trying goneovim.

In the meantime, I hope you'll consider putting info on mapping M- in the README, as the current behavior can cause a headache for anyone trying to migrate their config from other vim clients (probably the vast majority of your potential users!)

**Comment by akiyosi** [comment]
Thanks for letting me know how you use vim in your environment.
We'll try to improve the README to address the points you've made.

Please tell me one more thing.
Do you have `macmeta` settings enabled in MacVim? (ref: https://stackoverflow.com/questions/11903889/how-to-not-get-special-characters-in-place-of-meta-key-combinations-for-vim-on-o)

**Comment by smackesey** [comment]
Yes, I understand that's what make M- work in MacVim.

**Comment by akiyosi** [comment]
Hi
This feature has been added in v0.4.7.
You can use `<M-` mapping by adding the following to `~/.config/goneovim/setting.toml`

```
[Editor]
Macmeta = true
```
