### ISSUE TITLE
goneovim suddenly crash

### ISSUE THREAD

**Issue by eyalk5** [akiyosi/goneovim#138]
Jun 27 19:06:23 Eyals-MacBook-Pro com.apple.xpc.launchd[1] (com.ident.goneovim.44876[99046]): Service exited with abnormal code: 2

How to debug? Is there a log?

It happens when closing buffers.

**Comment by akiyosi** [comment]
Hi,
Thanks for the report.
Sorry, I have a plan to implemen log output feature, but not yet.😅

Is this problem the HEAD of goneovim? Or is it a specific release?

**Comment by eyalk5** [comment]
It happens with one of the recent versions, from 10/06. But it isn't reliably reproducible.

**Comment by Aletz-Arce** [comment]
> It happens with one of the recent versions, from 10/06. But it isn't reliably reproducible.

Hi @eyalk5 ,
Maybe you should try the last version generated by Github Actions, in my case with last version 
i no longer have sudden crash.
Regards

**Comment by eyalk5** [comment]
No crashes so far. will wait a bit and close.

**Comment by eyalk5** [comment]
I got 5 full dumps. Unfortunately no full symbols. Not sure what to do with all this.

**Comment by akiyosi** [comment]
@eyalk5
Hi, 
Thank you for your contribution.

Are you using gonvim-fuzzy?
If you are using it, the application's crash problem may be due to the fuzzy finder feature inside gonvim-fuzzy and Goneovim.

Goneovim can't fix all race conditions, and the only problem still remains to be the one related to handling fuzzy finder. I'd like to fix this, but it's a bit difficult and hasn't been done yet.

**Comment by eyalk5** [comment]
Hi, I am not using gonvim-fuzzy at all. Probably some of them relate to nvim.

**Comment by eyalk11** [comment]
Anything new with the crash log ? (It is the same user, just different account... :) ) I get some crashes that I couldn't debug (too often).

**Comment by akiyosi** [comment]
Hi,
You can start it in debug mode by specifying `--debug` from the command line. You can also output the debug log to a directory other than the current directory by specifying something like `--debug=\path\to\debug.log`.

The crash of Goneovim may be due to the involvement of certain plugins and one way to isolate it is to see if the event occurs with `-u NONE` specified.

**Comment by akiyosi** [comment]
Closed.
