### ISSUE TITLE
too slow in startup

### ISSUE THREAD

**Issue by bon-ami** [akiyosi/goneovim#182]
This starts considerably more slowly than Neovim(qt). I have been using this for months, yet I have decided to switch back to neovim for now.
BTW, I use AutoHotkey to start this. It does not show in FG, but starts as blocked by other FG windows. Neovim works fine. Windows 10.

**Comment by akiyosi** [comment]
hi
Thanks for the issue report.
Yes, I am aware of this problem as I also use Windows at work, and the improvement in startup speed is a TODO.

I would like to check, how long are the startup speeds of neovim-qt and goneovim respectively? (even if you can feel it)

**Comment by gwojan** [comment]
I just recently started experimenting with `goneovim` and `nvim-qt` seems to start 5 or 6 times faster -- especially when starting fullscreen. I routinely use a dark theme for `vim` and `neovim` so the other really annoying thing about `goneovim` startup is the white canvas being displayed prior to the theme being applied. It's very jarring...

**Comment by akiyosi** [comment]
@gwojan 
Thanks for your opinion.
What your OS?

> I routinely use a dark theme for vim and neovim so the other really annoying thing about goneovim startup is the white canvas being displayed prior to the theme being applied. It's very jarring...

Hmmm, I know. Actually, in the previous version of goneovim, the specification was that the window would not be displayed until the entire application color was determined. I changed this specification to show the window first to make it look more sensible and quicker to launch, since the color information is provided by neovim and it takes a lot of time to apply the color to the entire application.
This is entirely a matter of taste, but I'm going to reconsider this specification for a moment.

**Comment by gwojan** [comment]
@akiyosi I'm currently using `Microsoft Windows 10 Enterprise, Version 1909 (OS Build 18363.1198)`. I apologize, I should have included that in the first place.

I also use the nightly Windows builds of `Neovim 0.5` if that makes any difference at all.

**Comment by akiyosi** [comment]
@bon-ami 
hi
Sorry for late reply.
I have been working on solving the boot time issue in Windows. If you have time, I would appreciate it if you could check if the problem has improved somewhat. You can get the binary below.

https://github.com/akiyosi/goneovim/suites/1733424569/artifacts/32846679

**Comment by bon-ami** [comment]
Thank you Aki Yosi. It runs fine to me.

**Comment by akiyosi** [comment]
Closed.
