### ISSUE TITLE
Why do build artifacts have such a large size?

### ISSUE THREAD

**Issue by MuhammedZakir** [akiyosi/goneovim#195]
Why do build artifacts have such a large size? Are you perhaps including Qt libs?

Latest build artifacts' sizes - https://github.com/akiyosi/goneovim/actions/runs/566185612#artifacts:

| Name | Size |
| ---- | ---- |
| Goneovim-latest-linux-5.13.0 | 302 MB |
| Goneovim-latest-linux-5.14.1 | 300 MB |
| Goneovim-latest-linux-5.15.1 | 303 MB |
| Goneovim-latest-macos-5.13.0 | 596 MB |
| Goneovim-latest-macos-5.14.1 | 643 MB |
| Goneovim-latest-macos-5.15.1 | 578 MB |
| Goneovim-latest-win64-5.12.6 | 219 MB |
| Goneovim-latest-win64-5.13.0 | 234 MB |
| Goneovim-latest-win64-5.14.1 | 240 MB  |

**Comment by akiyosi** [comment]
Hi :)
Hmmm, actually I don't really understand that part either.
Now that I've compared them in MacOS, it seems that most of the size difference is due to the `QtWebEngineCore.framework`.
I have set `QT_DEBUG=false` as an environment variable at build time, but for some reason or other, it may be that the debug version of `QtWebEngineProcess.app` is included.

**Comment by MuhammedZakir** [comment]
I see. I will post here if I can find anything about this. Thanks for the app, btw! :smile:

**Comment by MuhammedZakir** [comment]
It looks like package is dynamically linked? Is it possible to generate a statically linked binary? Considering there are some files to be including, maybe AppImage [1] is a better option?

[1] https://appimage.org/
[2] https://github.com/probonopd/linuxdeployqt

**Comment by akiyosi** [comment]
Hi,
Thanks for the research.

For the first point about static builds, I don't think it is possible because this project includes qtwebengineprocess. If there is any information for static build including qtwebengineprocess, I would like to know it.

For the second point, this project uses the build command that provides qt binding for Go([therecipe/qt](https://github.com/therecipe/qt)), and the build also uses the build command provided by the tool. And as far as I know, the build command does not use tools such as `linuxdeployqt` internally at the moment. See https://github.com/therecipe/qt/issues/787

**Comment by MuhammedZakir** [comment]
It looks like release builds are also of large size. When I looked the size of extracted dir of release build archive, it was also 300+ mb. :-( Is there no other way? Maybe ask in "therecipe/qt" repo or in Reddit? Someone may have an answer.

**Comment by akiyosi** [comment]
I think one big reason is that we are using QtWebengineProcess for markdown preview. qtwebengineprocess is an independent process based on chromium and its binary size is large.
https://doc.qt.io/qt-5/qtwebengine-overview.html

There is a plan to cut out the markdown preview functionality, including qtwebengine, into a separate plugin, but no work has been done yet.
https://github.com/akiyosi/goneovim/pull/174

**Comment by MuhammedZakir** [comment]
Qt-WebEngine alternatives I know:

1. https://github.com/webview/webview
2. https://github.com/cztomczak/cef2go
3. https://github.com/qt/qtwebkit

**Comment by akiyosi** [comment]
This issue has been resolved.
Closed.
