### ISSUE TITLE
`<c-e>` mapping gets activated in mouse scrolling 

### ISSUE THREAD

**Issue by eyalk11** [akiyosi/goneovim#254]
Hi, 
Every time I do scroll down (on windows) , I get `^]1` appears with a new line (in insert mode).

It doesn't happen on `-u NONE` , so it could have been a bad mapping, but I have checked this. I still think it is  kind of a bug of goneovim. It doesn't happen in neovim-qt  ! or on nvim 

I tried once `set mouse=` and it solved it , but in few other attempts it didn't. It is very strange. WDYT?

**Comment by akiyosi** [comment]
Hi :) 
Goneovim uses <C-e> and <C-y> for mouse scrolling. If you have a keymaps set for these keys, you may experience unexpected character input, etc.
Do you have keymaps set for these keys?

Note that although Goneovim internally detects keymaps and implements a simple workaround to input the ScrollWheelUp/Down key if a keymap is existing, it may not work effectively depending on the user's settings.

**Comment by eyalk11** [comment]
`Goneovim uses and for` what is `and for` ?  Thanks :)

**Comment by akiyosi** [comment]
Oh, sorry for typo :P 
Goneovim uses C-e, C-y for mouse scrolling.

**Comment by eyalk11** [comment]
Hi, yes I have remapped `<c-e>`. 

Can you use (the equiv of) `norm!` instead of `norm`? I think it is a bug.

**Comment by akiyosi** [comment]
Goneovim internally uses `<C-e>` and `<C-y>` for scrolling, but it is not a Vim layer handling and there are no mapping settings.

On the other hand, as I mentioned in my first reply, Goneovim has a mechanism to detect whether the user has mapped these keys or not. The problem seems to be that this detection mechanism is not working properly in your environment.
Therefore, I have created a binary that adds debug log output for the relevant process. Could you please get the latest build below, try mouse scrolling in the mode that outputs debug logs, and share the output debug logs on Gist or something?

https://github.com/akiyosi/goneovim/actions/runs/1143207439

For debug mode, start Goneovim on the command line as follows:

``` cmd
C:\Path\To\goneovim.exe --debug=C:\debug.log
```

**Comment by eyalk11** [comment]
Hi, well, in this version there wasn't an issue. I might had not the latest version(sorry, missed the action tab).
