### ISSUE TITLE
Transparency issues

### ISSUE THREAD

**Issue by LoipesMas** [akiyosi/goneovim#268]
When Editor is transparent, some popups (I'm not sure what exactly are they called) are also transparent which makes them unreadable.

This is when I do `:hi`:
![image](https://user-images.githubusercontent.com/46327403/134499759-c5549b09-f823-4f6f-a052-b65b233478cc.png)
As you can see, the last line is unreadable because of status line. Other line are readable because there is no text behind them, but if I would open a file they would be unreadable.

settings.toml is just
```
[Editor]
Transparent = 0.7
```

Also happens with `goneovim -u NONE`. On 0.4.12 and latest build.

My system: archlinux with dwm (although I don't think this should be the issue)

I think those "popups" (or whatever they are called) should always have solid background.

**Comment by akiyosi** [comment]
Hi, sorry for the late reply.

This specification is the result of a straightforward implementation of neovim's multigrid ui, but as you pointed out, I also understood that some contents are difficult to identify when the message window is translucent. 
I have fixed the following CI build so that only the message window is not transparent. 

https://github.com/akiyosi/goneovim/actions/runs/1272360417

If you want the message window to be transparent, explicitly set the transparency in the Message section.

``` toml
[Editor]
Transparent = 0.7
#...

[Message]
Transparent = 0.8
```

I would appreciate it if you would provide feedback.

**Comment by LoipesMas** [comment]
It looks good now, thanks.

Is it possible to do the same thing for the autocompletion?

![image](https://user-images.githubusercontent.com/46327403/134771637-13a100dc-64f0-4b59-af07-533c4e064b47.png)

**Comment by akiyosi** [comment]
@LoipesMas 
I've included that fix as well.

https://github.com/akiyosi/goneovim/actions/runs/1275401418

Unlike the message window, the completion window and float window have their own transparency settings, which I've made them follow.

**Comment by LoipesMas** [comment]
I looks like now it is a bit darker but still transparent (even though I only have editor transparency in `settings.toml`)

**Comment by akiyosi** [comment]
@LoipesMas 
Thanks for your confirm.
I had implemented them to be multiplied by the transparency of the editor as well.
After re-examining your feedback, I decided to make those transparency independent of the editor transparency. 
So if you want to control the transparency of the completion menu, `set pumblend`, and if you want to control the transparency of the float window, `set winblend` in init.vim.

Please check the following CI build.
https://github.com/akiyosi/goneovim/actions/runs/1293202156

**Comment by LoipesMas** [comment]
It works as expected now, thanks!
