### ISSUE TITLE
Font sharpness issue when changing window screen on macOS

### ISSUE THREAD

**Issue by colinux** [akiyosi/goneovim#284]
First, thanks for this amazing GUI.

I have an external monitor. Most of time I'm starting goneovim from a terminal. When I'm moving the window to the external monitor, the font loses sharpness on this other monitor (I don't know if _sharpness_ is the exact term). This happens in both directions (ie. if i'm starting goneovim in external monitor it's fine, but problem occurs when moving window to the main screen).

I can reproduce that with my custom configs, and default neovim & goneovim configs, on a M1 and an old macbook pro, and with 0.4.12 & 0.4.13 versions.
I don't have this issue with neovim.

I attached screenshots for comparison.

On monitor launching goneovim :
![normal](https://user-images.githubusercontent.com/150279/142848513-fa208b5b-36ee-4a22-ae68-e886b5629698.png)

When switching monitor :
![not-normal](https://user-images.githubusercontent.com/150279/142848576-53b42fa5-911c-44c8-a03d-a676de0fa21d.png)

**Comment by akiyosi** [comment]
Hi :)
Thanks for this issue report.
I was able to reproduce this issue and am trying to fix it.
In my environment, the following CI build seems to have fixed the problem, but what about in your environment?

https://github.com/akiyosi/goneovim/actions/runs/1492795804

Since you seem to be M1, you can use the following package.
`Goneovim-latest-macos-5.15.2`

**Comment by colinux** [comment]
Hi ! 

Problem solved. Thanks a lot !
