### ISSUE TITLE
Invalid case of mac command key combination

### ISSUE THREAD

**Issue by xuliefeng** [akiyosi/goneovim#285]
hi,  i am upgrade to new version(0.4.13).
find Invalid case of mac command key combination(Not case sensitive),No problem with the old version

macos  10.15.7

**Comment by akiyosi** [comment]
Hi :D 
Thanks for the issue report.

What is the specific issue you are looking at?
Also, what is the expected behavior?

Also, sorry for not mentioning it in the release documentation, but v0.4.13 fixes some key combination behavior. Please refer to the following for details.

https://github.com/equalsraf/neovim-qt/issues/817
https://github.com/equalsraf/neovim-qt/pull/820

**Comment by akiyosi** [comment]
@xuliefeng 
thanks for reply!
Am I correct in understanding that you have accepted this spec change, changed your mapping, and the problem is solved?

**Comment by xuliefeng** [comment]
@akiyosi  
yes , thanks for you
this is good nvim gui
