### ISSUE TITLE
How can I make the cmdheight to be 2

### ISSUE THREAD

**Issue by Banana-Two** [akiyosi/goneovim#289]
In goneovim， the cmdheight is 3
![1](https://user-images.githubusercontent.com/62785154/143868718-f78f63cc-0f19-4caf-8cbc-338db8f61120.jpg)

But, in gvim I set it to be 2
![2](https://user-images.githubusercontent.com/62785154/143868737-d16b950e-985d-4e30-be65-0addae95c77c.jpg)
.

**Comment by akiyosi** [comment]
Hi :)

There is no specification for cmdheight to be 3 in goneovim.
On the other hand, goneovim calculates the number of rows and columns based on the size of the window and the size of the font, and runs nvim, but in the size calculation, there may be "extra space", for example, in the vertical axis, there may be "extra space" close to the height of the font at maximum.
I expect your point is due to such an extra space, though, for example, does the area change with resizing?

**Comment by Banana-Two** [comment]
@akiyosi 
Yes, I found that the distance between the cmdline and statusline will be bigger if I make the window of goneovim bigger.
If I make the height of goneovim to be 300, I get this picture
![1](https://user-images.githubusercontent.com/62785154/144533315-8d57ea7d-6
If i maximum it , I get this picture
![2](https://user-images.githubusercontent.com/62785154/144533411-8bbe823a-9f19-427e-9113-88ad3b9e1382.jpg)
e52-472a-abd8-9b746f44209c.jpg)
How can I make this distance smaller

**Comment by 13k** [comment]
> goneovim calculates the number of rows and columns based on the size of the window and the size of the font, and runs nvim, but in the size calculation, there may be "extra space", for example, in the vertical axis, there may be "extra space" close to the height of the font at maximum

Is it possible to implement a "rounding" logic (either up or down) on the window geometry values so that the window's (height, width) corresponds exactly to (lines * line_height, columns * column_width)?

This would possibly override the configuration values, but if the user is ok with that (which I would be), then it would resize the window accordingly and visually match the rendered content.

Ideally for me though, this idea would be expanded to set the window geometry in terms of `lines x columns`, as opposed to screen pixels. It's much more flexible, the configuration doesn't need to take into account which font/font_size combination it's currently set (which plays nice with font fallback) and the window simply resizes to the desired lines and columns asked for.

**Comment by akiyosi** [comment]
@13k 
Regarding your request, I have integrated a fix whereby the window size is changed in font metrics units. This specification is controlled by `WindowGeometryBasedOnFontmetrics`. To enable the setting, do the following

```toml
# ~/.config/goneovim/settings.toml
[Editor]
#...
WindowGeometryBasedOnFontmetrics = true
# ...
```

I would appreciate it if you could try to confirm that it works.

Note that the window size is calculated by `Width` and `Height` given in `settings.toml` and the specified font metrics, and the process is implemented in such a way that extra areas that are less than the font metrics are truncated.

Additionally, based on a comment made in another issue #296, `Margin` has been added to the configuration. This configuration item allows you to adjust the margin between the application content and the window.

It would be appreciated if you could check this as well.

You can find these changes in the following CI artifacts.
https://github.com/akiyosi/goneovim/actions/runs/1949983538

**Comment by 13k** [comment]
```
Gap = 0
Margin = 0
WindowGeometryBasedOnFontmetrics = true
```

on linux, there's a very small gap still showing on window launch (wayland, kde, amd gpu) that disappears as soon as I resize the window:

![20220308-171243](https://user-images.githubusercontent.com/4762/157317499-595ac2ae-c9d3-42d4-bc60-9b873667939b.png)

after resize:

![20220308-171301](https://user-images.githubusercontent.com/4762/157317528-66bbbac5-6b4e-40b8-8d7f-08537433c677.png)

this doesn't seem to happen on macos.

**Comment by akiyosi** [comment]
@13k 
Thanks for confirming.
Could you please check again as I have made improvements to the points you have pointed out? It is working fine on my end.

https://github.com/akiyosi/goneovim/actions/runs/1968705782

@Banana-Two 
It is fine to send it via email, but you do not need to compile it, and the artifacts are available for each job in Github Actions. 
Is access to this one also being blocked?
<img width="895" alt="2022-03-12 2 10 16" src="https://user-images.githubusercontent.com/8478977/157914995-b7af4311-6191-403b-9004-e97817a868d0.png">

**Comment by 13k** [comment]
sorry for the delay, work has been consuming for the last couple weeks.

I see the commit was merged to master, so I checked the latest master build and it seems to be correct:

![20220327-161014](https://user-images.githubusercontent.com/4762/160296848-ec9ae5f3-233d-4c74-9e13-6597d71e3d19.png)

Again, thanks for looking into it.

**Comment by Banana-Two** [comment]
@akiyosi 
I'm sorry! Only now did I find out that I missed the email information. Just after I found out about it, I tried the latest version. It's working properly now. Thanks very much！
![image](https://user-images.githubusercontent.com/62785154/160310675-16ebcc05-07ad-4473-a02f-3fae721deea9.png)
