### ISSUE TITLE
Problem with --server and (possibly) workspaces

### ISSUE THREAD

**Issue by yngwi** [akiyosi/goneovim#313]
Hi,

so far I'm using nvim-qt to connect to a headless neovim instance in docker containers using --server mode. This works well. 

I wanted to try the same in Goneovim but I think an error in startup that needs to be "confirmed" by pressing enter stops Goneovim from connecting. When I first attach nvim-qt to the headless instance (which works fine) and then start the Goneovim client using the same --server value, I am seeing `Error detected while processing UIEnter Autocommands for "*": E475: Invalid Argument: Channel doesn't exist.` in the nvim-qt window. After I press enter to confirm in nvim-qt, Goneovim connects and works just fine. Can someone help me figure out where this behaviour could come from? Could it be connected to the "Workspaces" functionality? Is it possible to disable this completely as I don't need it anyways and it creates a vim language file in my workspace root.

Thank you,
Daniel

**Comment by akiyosi** [comment]
Hi,
Thanks for this issue reporting.

I have investigated and fixed this problem.
Could you please check with the latest CI build below to see if the problem is also resolved in your environment?

https://github.com/akiyosi/goneovim/actions/runs/1762702113

By the way, as a matter of preference, goneovim also has the `--ssh` option, which is also useful. 
This attaches to the process after starting the nvim you are connecting to using ssh, unlike `--server` which attaches to the already started nvim instance.

**Comment by yngwi** [comment]
Indeed it works, with the CI build. Thank you! Also, thank you for the tip with --ssh. Maybe I'll use that sometime in the future, but for my workflow right now the --server version is a perfect match. Thank you for your quick support!
