### ISSUE TITLE
ctrl + shift +x map become useless in goneovim

### ISSUE THREAD

**Issue by fecet** [akiyosi/goneovim#352]
I set
```
noremap <C-H> :BufferLineCyclePrev<CR>
noremap <C-L> :BufferLineCycleNext<CR>
```
in my init and they work fine in a plain neovim. However, goneovim seems don't know what I just entered and result nothing when I "C-H"

**Comment by mars0i** [comment]
Hi @fecet.  (Just another Goneovim user here.)  Just thought I'd see if I could reproduce the problem.  I don't have your buffer line plugin, but it shouldn't matter.  

The title of the issue said "ctrl + shift +x".  I thought that `<C-H>`, etc. meant the same thing as `<C-h>`.  Is that not always correct?

I tried defining mappings in plain nvim and in Goneovim, and there was a difference, but not exactly what you are describing here.  What I found was that I can define different mappings for Ctrl-Shift-H vs. Ctrl-H in Goneovim, but not in plain nvim.  I'm using `<C-S-H>` for the first mapping, and `<C-H>` for the second mapping.

(However, I am on MacOS, and you might be on a different OS.  And I think that the reason that Ctrl-Shift-H and Ctrl-H can't be distinguished in plain nvim might have something to do with my terminal app (iTerm2) or the terminal settings.)

Maybe none of that is relevant to your problem, but since I don't have the same problem, it might matter which OS version of Goneovim this is.  (Also, you have probably done this, but if not maybe it's worth defining `<C-H>` and `<C-L>` to something other than the `:BufferLineCycle*` commands to see what happens, in case the problem is not with mappings but with how the buffer line plugin interacts with Goneovim.)

**Comment by fecet** [comment]
Thanks for your detailed explanation @akiyosi , map to "C-S-H" save my life!

**Comment by mars0i** [comment]
That's great.  I'm happy I could help!

**Comment by akiyosi** [comment]
@fecet @mars0i 
hi, sorry for late reply.
Generally, @mars0i's comments are the same as my perception. Thank you @mars0i 

This issue has been fixed in reference to changes made to neovim and neovim-qt. Please refer to the following issue for details.

https://github.com/neovim/neovim/issues/12037
https://github.com/equalsraf/neovim-qt/issues/817
