### ISSUE TITLE
Gitsigns

### ISSUE THREAD

**Issue by Mo8it** [akiyosi/goneovim#358]
The signs column is not continous at least with Gitsigns, see screenshot. Left is Goneovim, right is Neovim in the terminal Kitty.

![Screenshot from 2022-05-07 19-39-41](https://user-images.githubusercontent.com/76752051/167265620-cea6537e-b03e-4687-b7ea-7717163d34c2.png)

**Comment by akiyosi** [comment]
@Mo8it 
Hi, thanks for this issue post.
Do you have `linespace` set to 1 or larger(e.g. `set linespace=x` where x is >0)
if so the extra line spacing will make it look like this.
Also, is it a font issue?

**Comment by Mo8it** [comment]
This is my config:
```
[Editor]
SmoothScroll = true

[Cursor]
SmoothMove = true

[MiniMap]
Disable = false
```

I did not change fonts or linespace. I tried adding `Linespace = 0`, but it did not solve it.

I am using Linux btw (Fedora 35 with Gnome).

**Comment by Mo8it** [comment]
I think Neovide did not have this issue. So it is not a GUI font problem, I guess. (btw I switched to Goneovim because Neovide had very bad performance, at least on my laptop; thanks for Goneovim ^^)

**Comment by akiyosi** [comment]
@Mo8it 
Thanks for confirming. 
Could you please check that linespace is set in your init.vim and not in settings.toml?
Or run `echo &linespace` in your running goneovim to check the setting value.

**Comment by Mo8it** [comment]
`echo &linespace` shows the value 0.

**Comment by akiyosi** [comment]
@Mo8it 
Thanks for your confirming.

Hmmm, maybe this is a problem with Qt.
Goneovim calculates the font metrics on Qt's layer and uses the results to calculate the height of each line in the editor.
If linespace is 0, its height is completely set to the font height.

A workaround is to set a negative value to linespace (e.g. `set linespace=-1`). goneovim did not allow negative values for linespace, but now accepts negative values as well, since the following commit

https://github.com/akiyosi/goneovim/actions/runs/2305648657

**Comment by Mo8it** [comment]
`linespace=-6` is the first value that made the gutter line continuous. But now, the lines are too squashed. Here is a comparison: Neovim in Kitty is on the right side, Goneovim is on the left side.

![image](https://user-images.githubusercontent.com/76752051/167828514-6225691a-c487-4add-a93e-8db5b22b9186.png)

**Comment by akiyosi** [comment]
@Mo8it 
As mentioned above, this problem is due to Qt's handling of fonts, so the only fundamental solution is to use a different font with a font height that allows gitsigns to be continuous.

Also, I introduced a workaround for setting a negative value for linespace, but setting a negative value for linespace may cause problems in the drawing process. This is what the help says, and in fact it is also true for the drawing architecture of goneovim.

```
						*'linespace'* *'lsp'*
'linespace' 'lsp'	number	(default 0)
			global
			{only in the GUI}
	Number of pixel lines inserted between characters.  Useful if the font
	uses the full character cell height, making lines touch each other.
	When non-zero there is room for underlining.
	With some fonts there can be too much room between lines (to have
	space for ascents and descents).  Then it makes sense to set
	'linespace' to a negative value.  This may cause display problems
	though!
```

**Comment by Mo8it** [comment]
OK, thanks. I will close the issue.

@akiyosi  Are there any fonts that you would recommend?

**Comment by akiyosi** [comment]
@Mo8it 
Everyone has their own favorite, but I'm using JetBrainsMono Nerd Font.
There are also services like the following.

https://www.codingfont.com/

**Comment by Mo8it** [comment]
JetBrainsMono Nerd Font Mono

This font fixed it.
