### ISSUE TITLE
Bug: `goneovim.app` does not work (macOS)

### ISSUE THREAD

**Issue by chrisgrieser** [akiyosi/goneovim#417]
Opening the `goneovim.app` does not work on Mac. The result is an empty window, which does not respond to any keystrokes.
<img width="801" alt="Pasted image 2022-10-03 20 15 39" src="https://user-images.githubusercontent.com/73286100/193649270-909da029-0233-43d4-8927-64b556a50276.png">

When trying to open a file via "Open With",  goneovim opens up, but immediately closes afterwards.

However, using the `goneovim` in the terminal **does** work correctly. 
Opening `/Applications/goneovim.app/Contents/MacOS/goneovim` from the terminal does work, too.

---

```
- macOS 12.5.1 (M1)
- neovim 0.8.0
- goneovim 0.6.3
```
tried with default settings (no `settings.toml`)

**Comment by akiyosi** [comment]
Hi :)
Hmmm, it seems that on your machine, when the shell specified by $SHELL runs as a login shell, the neovim process is not being started with the name nvim because the PATH is not set up well enough. I think you need to add the location of the nvim file to your PATH, for example, to .bash_profile for bash or zprofile for zsh.
