### ISSUE TITLE
Telescope overlay transparency

### ISSUE THREAD

**Issue by bfulop** [akiyosi/goneovim#483]
Hello,

I have recently discovered that Goneovim offers **true transparency** when setting the `winblend` or `pumblend` options ! 🎉

Not only emulated transparency like you see in terminals, but I can actually see the text beneath the text of the popups! 👏

I've noticed however that for the Telescope pickers, the border area has a higher transparency than the inside of the overlay. The inside retains some transparency too, but it seems about only 50% of transparency of the border area.

In the attached image, the line `export type EOf =` is partially under the the Telescope file picker.
The letter `p` has some transparency while the rest of the text is hardly visible.

![Telescope over some text](https://github.com/akiyosi/goneovim/assets/1718128/21c24b8a-2a96-4bd8-ae93-af62d4bbb7d1)

This is of course not a breaking issue, just something I noticed...

My telescope settings:

```
telescope.setup {
  tiebreak = function() return false end,
  defaults = {
    winblend = 15,
    path_display = {
      truncate = 2
    },
...
   }
  }
}
```

And an example of a hover popup that shows the "true transparency", behind the `<R, E, A>` text

<img width="304" alt="true transparency" src="https://github.com/akiyosi/goneovim/assets/1718128/10737211-4631-4521-8a31-abd001833061">

**Comment by akiyosi** [comment]
@bfulop 
Hi :)
Yes, goneovim supports the `winblend`, `pumblend` option.
Regarding the telescope issue you pointed out, this is because telescope's UI consists of multiple float windows stacked on top of each other.

Goneovim's UI is a multi-grid UI, where each buffer or window is drawn on a separate sheet, called a grid. In contrast, TUI and Neovim-qt are single-grid, meaning that all buffers and windows are represented on a single grid.
This difference allows, for example, multi-grid UIs to achieve full transparency instead of emulated transparency. On the other hand, due to the architecture of the multigrid UI, when multiple transparent windows overlap, the content at the bottom is more difficult to see than if it were covered by a single transparent window.

**Comment by bfulop** [comment]
Hello akiyosi,

Thanks for the detailed explanation! It's not a big issue, and I understand now that it's more on the Telescope side to potentially add this improvement.

**Comment by bfulop** [comment]
Update:

I added `border = false` and it seems to remove the extra level of nesting of the overlays in Telescope. This solved the issue for me.
