### ISSUE TITLE
Some files types icons shown incorrectly

### ISSUE THREAD

**Issue by damanis** [akiyosi/goneovim#513]
Hi @akiyosi,

Goneovim version: 0.6.8
nvim version (latest snapshot): v0.10.0-dev-2000+g6fa0f303d

Icons of some files types (not for all) are not shown properly. On screenshot `telescope` window, but same in `lualine` (or `galaxyline`).
I'm note sure they are relevant: the font taken from nerd font project, `nvim-web-devicons` installed.
It is not clear where the problem, but all icons shown properly in neovim without GUI or in [neovide](https://github.com/neovide/neovide).

![image](https://github.com/akiyosi/goneovim/assets/65733488/661920ed-38fa-46ed-8916-9f2ef0f49ad8)

**Comment by akiyosi** [comment]
@damanis 
Thanks for the report!
Does this problem still occur in v0.6.7?

**Comment by damanis** [comment]
@akiyosi 
In `v0.6.7` same.

**Comment by akiyosi** [comment]
@damanis 
Perhaps the font files already installed on your OS are out of date.
Try getting the latest version of your preferred font from the following link and reinstall it.
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts

It seems that Neovide displays well because Neovide embeds the Nerd Font font family inside the application, based on the source code below.
https://github.com/neovide/neovide/blob/main/src/renderer/fonts/font_loader.rs#L13

**Comment by damanis** [comment]
@akiyosi 

Yes, with new font version works properly. Thank you.
