### ISSUE TITLE
vimtex exits visual mode on compiling 

### ISSUE THREAD

**Issue by eyalk5** [akiyosi/goneovim#97]
Hi,

This only happens on neovim-qt and goneovim. Not on TUI.

See https://github.com/lervag/vimtex/issues/1597 

Can you make an educated guess as to why it happens?

I wrote the same issue here: 
https://github.com/equalsraf/neovim-qt/issues/645

**Comment by akiyosi** [comment]
Hi
I tried to reproduce the problem but could not yet.

> Can you make an educated guess as to why it happens?

Neovim's GUI is the front end of Neovim. In particular, switching modes, drawing text simply interpret the events processed and dispatched by Neovim and draw them on the screen. If the interpretation on the GUI side is sufficient, this problem may be due to a problem with Nvim's External UI feature.

If you can debug Goneovim in your environment, you can add debug code etc. to the following event handler and check the events that Neovim sends.

https://github.com/akiyosi/goneovim/blob/master/editor/workspace.go#L710-L855

**Comment by eyalk5** [comment]
This happens due to callbacks. I disabled them and it is OK. I guess I am too busy to debug this further. It runs `nvr --remote-expr "vimtex#compiler#callback(1)" `.

**Comment by eyalk5** [comment]
nvr bug. Solved. https://github.com/neovim/neovim/issues/12165
